name: Aria2 Docker Push

on:
  workflow_dispatch:
  
  pull_request:
    branches: 'master'
    paths:
      - "aria2/Dockerfile"
      - "aria2/aria2.conf"
      - "aria2/run_aria2_docker.sh"
      - "!**.MD"
      - "!LICENSE"
      - "!.gitignore"
  push:
    branches: 'master'
    paths:
      - "aria2/Dockerfile"
      - "aria2/aria2.conf"
      - "aria2/run_aria2_docker.sh"
      - "!**.MD"
      - "!LICENSE"
      - "!.gitignore"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./aria2
          push: true
          tags: xforce/aria2:latest
